### ISSUE TITLE
macOS: App name is the slug version of the app, not the 'friendly name'

### ISSUE THREAD

**Issue by JeffersonBledsoe** [music-assistant/companion#12]
It would be nice if the app had a name of `Music assistant` rather than the internal `productName`

<img width="1089" alt="Screenshot 2023-11-21 at 12 01 50 pm" src="https://github.com/music-assistant/music-assistant-desktop/assets/30210785/8d5e4eb6-8fcc-46b3-9e93-1a9e89a615cb">
<img width="258" alt="Screenshot 2023-11-21 at 12 01 42 pm" src="https://github.com/music-assistant/music-assistant-desktop/assets/30210785/30f5c8ae-69c5-4eec-bac8-50d8cc135dbf">

**Comment by arctixdev** [comment]
I think this might be fixed now. Im gonna try to release a new version later today but im not sure it will work because i dont have the rights to change the signing keys in the github repo.

**Comment by JeffersonBledsoe** [comment]
Thanks for the quick fix! I'll give it a try locally shortly and report back if there's any issues
