### ISSUE TITLE
macOS: Window position and size isn't remembered

### ISSUE THREAD

**Issue by JeffersonBledsoe** [music-assistant/companion#14]
The app always opens in a 500x500 square near the centre of the screen. It should follow the default mac behaviour of re-opening at the previous size and position.

See the following for ideas on how to solve it:

- https://github.com/tauri-apps/tauri/issues/3740
- https://github.com/tauri-apps/tauri-plugin-window-state
- https://github.com/tauri-apps/plugins-workspace/issues/250

**Comment by arctixdev** [comment]
Hi, thanks alot for the report. I wasnt aware of this because i don use macos normally. But really great suggestion! Ive added the plugin you linked to. Next version should include this.

**Comment by JeffersonBledsoe** [comment]
Thanks for the quick fix! I'll give it a try locally shortly and report back if there's any issues.
