### ISSUE TITLE
None of the macOS apps work

### ISSUE THREAD

**Issue by Smarthome-Creator** [music-assistant/companion#23]
I have tried all three variants on my MacBook Air with M2.

- The ARM version cannot be opened because it is damaged.
- The x64 Intel version closes the window immediately after opening.
- The Brew version cannot be installed because the SHA value does not match.

**Comment by JeffersonBledsoe** [comment]
@Smarthome-Creator Looks like this is a permission error. I got the following when building the app in dev mode:

```rs
Failed to get output devices: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
```

Happy for me to update this issue with the details as I dig into it?

**Comment by Smarthome-Creator** [comment]
@JeffersonBledsoe , unfortunately, I have no idea about programming, I just build all the great things you do. ;-) I tested the Linux app today on Ubuntu and will test it later on my Steam Deck. The app ran flawlessly on Ubuntu.

**Comment by agdamsbo** [comment]
Following as I have the exact same problem running on an M1 Macbook Air

**Comment by Smarthome-Creator** [comment]
Thank you for staying tuned. Intel and ARM versions are now running.

Unfortunately, the Brew installation still has the same problem.

**Comment by arctixdev** [comment]
I think I fixed the homebrew tap now
