### ISSUE TITLE
Can't connect to HTTPS server

### ISSUE THREAD

**Issue by megatwig** [music-assistant/companion#26]
The app asks for an IP/hostname and port, but doesn't allow you to specify that HTTPS should be used instead of HTTP.

I have a reverse proxy set up to serve the UI on a custom domain over HTTPS on port 443.

**Comment by cociweb** [comment]
With the above mentioned PR, it made me possible to connect with https. If there is no further obstacles, then we can close this ticket.

**Comment by arctixdev** [comment]
Oh yeah, thanks
