### ISSUE TITLE
missing dependencies on debian

### ISSUE THREAD

**Issue by cociweb** [music-assistant/companion#28]
Hello,

I'm getting the following log messages of the debian companion app, when i select the "show info" submenu of a yt (or local media)  music element:
```
$ music-assistant-companion 
WebKit wasn't able to find a WebVTT encoder. Subtitles handling will be degraded unless gst-plugins-bad is installed.
GStreamer element fakevideosink not found. Please install it
WebKit wasn't able to find a WebVTT encoder. Subtitles handling will be degraded unless gst-plugins-bad is installed.

(WebKitWebProcess:26872): GStreamer-Audio-CRITICAL **: 23:19:00.643: file ../gst-libs/gst/audio/gstaudioringbuffer.c: line 2054 (gst_audio_ring_buffer_set_channel_positions): should not be reached

(WebKitWebProcess:26872): GStreamer-Audio-CRITICAL **: 23:19:00.934: file ../gst-libs/gst/audio/gstaudioringbuffer.c: line 2054 (gst_audio_ring_buffer_set_channel_positions): should not be reached

```

**Comment by c-mahn** [comment]
Hello,

I would like to add the following dependency-error to this issue:

`music-assistant-companion: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

**Comment by cociweb** [comment]
With v0.0.45 the original dependency error disappears.
Thank's for your great job!

**Comment by arctixdev** [comment]
Nice! I have no idea what change actually fixed it but :shrug: Glad its working

**Comment by mrmaceurope** [comment]
I still face the issue on Debian on ChromeOS, and I need to do the symbolic links mention by @c-mahn.

```
music-assistant-companion: /lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_0' not found (required by music-assistant-companion)
music-assistant-companion: /lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_0' not found (required by music-assistant-companion)
```

**Comment by arctixdev** [comment]
Hmm yeah, honestly I no idea why this is happening..

**Comment by mrmaceurope** [comment]
Well for now, as a kind of a workaround, I'm using the web app and have created it as a PWA on the Chromebook and in the Chrome browser. Works perfectly.

**Comment by cociweb** [comment]
@mrmaceurope, @c-mahn which version of the app are you using? .deb or .appimage? Can you please share more of your os and environment? (If you are **not** using a .deb package on a debian/fork of debian os, then I suggest to open a new ticket.)

**Comment by mrmaceurope** [comment]
I downloaded the latest deb package, version v0.0.45. I tried to install it simply, just by clicking it on the https://music-assistant.io/companion-app/#debian-and-debian-based-distrobutions, and then launched the package from the Chrome OS side, which started the installation but ended with error. Since this installation method doesn't generally provide many details, I tried installing the package from the terminal - where I got the same mentioned errors as listed above and reported by @c-mahn.    

The ChromeOS Debian OS information
```
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by c-mahn** [comment]
@cociweb I have currently installed the version 0.0.45 as amd64.deb under Debian 12. My current error-message after having done the steps above is still the following:
```music-assistant-companion: /lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_0' not found (required by music-assistant-companion)
music-assistant-companion: /lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_0' not found (required by music-assistant-companion)```

**Comment by GrumpyMeow** [comment]
Same here..
`music-assistant-companion: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

**Comment by cociweb** [comment]
1) ok, first of all, we need to locate your libraries:
depending on your flavour, you have to check, where it is with `which`/`locate`/`whereis` command. Eg:
```
$ whereis libssl.so.3 
$ whereis libssl.so.1.1
$ whereis libcrypto.so.3
$ whereis libcrypto.so.1.1
``` 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You should get the same path for all of them. Something like this:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`[/usr/local/bin/openssl](libssl.so.3: /usr/lib/x86_64-linux-gnu/libssl.so.3)`

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(if none of them, available install one of them)

2) You need to add the path to your system environment (Something like this):
`export LD_LIBRARY_PATH= /usr/lib/x86_64-linux-gnu` or `export LD_LIBRARY_PATH=/usr/local/lib`

3) it should work now, until system restart. If you would like to do it as a permanent setting, you need to append it to your ~/.bashrc. Eg:
`echo "export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu" >> ~/.bashrc`
or
`echo "export LD_LIBRARY_PATH=/usr/local/lib" >> ~/.bashrc`

**Comment by arctixdev** [comment]
Hey I think i found the issue, could you guys try the new version (v0.0.54)? I did a lot of core changes and updated to the tauri 2.0 beta and also changed the openssl dependency to use vendored version.

**Comment by arctixdev** [comment]
Merging with #11

**Comment by arctixdev** [comment]
Actually in 54 another issue arose, so its not fixed yet..

**Comment by cociweb** [comment]
@arctixdev, maybe we could add libssl3 after libssl-dev (libssl-dev is based on libssl1.1) during [build time](https://github.com/music-assistant/companion/blob/2d706a76b31e9cdc726a67edb53b7ae57ecfa043/.github/workflows/build.yaml#L94).

**Comment by arctixdev** [comment]
Yeah that could also help. Right now I am facing an error with the builds not getting uploaded to Github. But I will try a quick workaround now and see if it fixes it

**Comment by cociweb** [comment]
[off]

> Yeah that could also help. Right now I am facing an error with the builds not getting uploaded to Github. But I will try a quick workaround just for now

You have /home/runner/work/companion/companion/src-tauri/target/release/bundle/deb/Music Assistant Companion_0.0.56_amd64.deb
instead of /home/runner/work/companion/companion/src-tauri/target/release/bundle/deb/music-assistant-companion_0.0.56_amd64.deb
 in https://github.com/music-assistant/companion/actions/runs/9341298597/job/25707905643#step:11:283
 
 only rpm is ok.

**Comment by arctixdev** [comment]
Could you try the new version? (v0.0.57)

**Comment by arctixdev** [comment]
Yeah i screwed up the path a few times....

**Comment by cociweb** [comment]
Well, I had no issue with 0.45. but with 0.57 I've got another (new) one:
music-assistant-companion: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by music-assistant-companion)

**Comment by arctixdev** [comment]
Oh damn.... Well, i am heading for bed now. I am pretty busy for the next couple of days. So fixing this will probably get delayed a bit... sorry. Till then you should be able to just continue to use v45

**Comment by arctixdev** [comment]
Actually it looks like its just because i switched it to build on ubuntu 24.04 https://tauri.app/v1/guides/building/linux/#limitations i will give it a shot now

**Comment by cociweb** [comment]
umm, in the meantime I see you have upgraded the build environment from ubuntu 20.04 to 24.04. on this release, the libssl3 is identical with [libssl4t64](https://packages.ubuntu.com/noble/libssl3t64). [libssl-dev](https://packages.ubuntu.com/noble/libssl-dev) is lies on the same package libssl3t64. which have further dependency the [libc6](https://packages.ubuntu.com/noble/libc6).
So on 24.04 there is no further benefit to add libssl3, rather we need to investigate the above mentioned new libc6 dependency. :)

**Comment by arctixdev** [comment]
Hm yeah... Looks like there are no runners picking up the ubuntu 18 job https://github.com/music-assistant/companion/actions/runs/9341463384/job/25708266887 :laughing: Gonna try 20 again

**Comment by cociweb** [comment]
my recommendation is to try with 22.04 since libssl3 is introduced on jammy.

**Comment by arctixdev** [comment]
Ah ok, yeah... Just tried with 20 now but can update if it dosnt fix it. Just thought to go as low as possible to support as many versions as possible

**Comment by arctixdev** [comment]
Ok i am gonna go to bed now. I am way to tired to deal with this now :rofl:

**Comment by arctixdev** [comment]
If you want you can create a pr and I could run the action to test it. But dont feel obligated to do so

**Comment by arctixdev** [comment]
Couldnt help myself, got the build working in ubuntu 22, could you maybe test the newest release?

**Comment by cociweb** [comment]
> Couldnt help myself, got the build working in ubuntu 22, could you maybe test the newest release?

As of now (0.0.65) it is working for me again, but I had no issues with incorrect ssl version in the past, so we need another confirmation from the guys above.

As a plus, the relaunch of the app is working again. (y)

**Comment by arctixdev** [comment]
Ah super cool!

**Comment by c-mahn** [comment]
Version 0.0.65 seems to has fixed my issues.

**Comment by arctixdev** [comment]
Ok super cool, closing this issue now then. If anyone has issue just comment / reopen
