### ISSUE TITLE
Documentation: Top links do not point to latest release

### ISSUE THREAD

**Issue by timmo001** [music-assistant/companion#31]
The top links do not point to the latest version of the application.

![image](https://github.com/music-assistant/companion/assets/28114703/79557fe3-7fb4-4dcb-b316-6e94e56af268)

Page:
https://music-assistant.io/companion-app/

**Comment by arctixdev** [comment]
Thanks for the issue! Fixed in this pr: https://github.com/music-assistant/music-assistant.github.io/pull/46
Once its approved it should update on the website
