### ISSUE TITLE
Download links in README are broken

### ISSUE THREAD

**Issue by marcoraddatz** [music-assistant/companion#35]
I'm new to the project and think that you've recently named the repo, because the download links are broken.

In the README:
https://github.com/music-assistant/music-assistant-desktop/releases/download/v0.0.45/music-assistant-companion_0.0.45_aarch64.dmg

In the release:
https://github.com/music-assistant/companion/releases/download/v0.0.45/Music.Assistant.Companion_0.0.45_aarch64.dmg

I could add a PR, but think that you auto-generate them?!

**Comment by arctixdev** [comment]
Ah thanks, fixing now!
