### ISSUE TITLE
Trick to getting into discord group?

### ISSUE THREAD

**Issue by greyfence** [music-assistant/companion#52]
Is there a trick to getting into the Music Assistant discord channel?  It says to click on the Thumbs Up reaction to get verified.  What does that mean?   Clicking on the icon did nothing.

**Comment by OzGav** [comment]
There is no trick. When you click on that you should then see a bunch of new channels. People are joining everyday without issue. If you can’t get in then tell me your discord nickname and I will have a look.

**Comment by greyfence** [comment]
My nickname is johnd126.  I'm connecting using the newest version of Firefox.

**Comment by OzGav** [comment]
I don’t know why clicking the thumbs up isn’t working for you but I have done it manually. You should be able to see all the channels now.

**Comment by leobeg** [comment]
Same for me. Is the verify bot still broken?

**Comment by leobeg** [comment]
> [@leobeg](https://github.com/leobeg) do you have a verified email in Discord?

Yeah I also have 2FA enabled. My username on DC is the same as on GitHub

**Comment by OzGav** [comment]
Not sure then as 10s of people join per day. I’ll verify you manually
